spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationPreFilter
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationPreFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8000"
              - "http://localhost:8100"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
logging:
  level:
    org:
      springframework: DEBUG
server:
  port: 4000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

gateway:
  excludedUrl: /api/auth/**
keyStore:
  path: keystore.jks
  password: password
  alias: auth-server
