spring:
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # Cache expiration time (1 hour)
  data:
    redis:
      host: redis
      port: 6379
  application:
    name: order-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
feign:
  client:
    config:
      default:
        loggerLevel: full
keyStore:
  path: keystore.jks
  password: password
server:
  servlet:
    context-path: /api
  port: 8200

logging:
  level:
    org:
      springframework: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "metrics"

  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enable: true